
default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vue_app_db_dev
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: vue_app_db_test

production:
  <<: *default
  database: vue_app_db_prod
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
